import { readdirSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";
import { describe, expect, it } from "vitest";

/**
 * Icon alpha contract (guardrail §6 / INV-09, audit INV-009): the `any`
 * matrix ships transparent PNGs; maskable, the apple-touch tile, and the
 * favicons are fully opaque (iOS expects a filled square and applies its own
 * mask). The suite is generated by scripts/generate-icons.mjs — this test
 * exists so a regeneration that flattens (or un-flattens) the wrong set fails
 * the gate instead of shipping.
 *
 * The App Router convention files (`src/app/icon0.svg`, `icon1.png`,
 * `apple-icon.png`) used to be listed here. They are gone: layout.tsx now
 * exports `metadata.icons`, which suppresses the convention links entirely, so
 * keeping the files would have shipped three assets nothing referenced.
 */
const ROOT = join(__dirname, "..", "..");
const ICONS = join(ROOT, "public", "icons");

async function raw(file: string) {
  const img = sharp(file);
  const meta = await img.metadata();
  const { data, info } = await img
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  return { meta, data, info };
}

function cornerAlphas(data: Buffer, width: number, height: number) {
  const px = (x: number, y: number) => data[(y * width + x) * 4 + 3];
  return [px(0, 0), px(width - 1, 0), px(0, height - 1), px(width - 1, height - 1)];
}

function minAlpha(data: Buffer) {
  let min = 255;
  for (let i = 3; i < data.length; i += 4) {
    const a = data[i];
    if (a !== undefined && a < min) min = a;
  }
  return min;
}

describe("icon alpha contract (transparent any-matrix, opaque masked set)", () => {
  const anyMatrix = readdirSync(ICONS).filter((f) => /^icon-\d+\.png$/.test(f));

  it("the any-matrix is present", () => {
    expect(anyMatrix.length).toBeGreaterThanOrEqual(13);
  });

  for (const file of anyMatrix) {
    it(`${file} keeps a transparent plate (alpha corners)`, async () => {
      const { meta, data, info } = await raw(join(ICONS, file));
      expect(meta.hasAlpha, "any-matrix icons must carry an alpha channel").toBe(true);
      for (const a of cornerAlphas(data, info.width, info.height)) {
        expect(a, "corner pixels outside the rounded plate must be transparent").toBe(0);
      }
    });
  }

  const opaqueSet = [
    join(ICONS, "maskable-192.png"),
    join(ICONS, "maskable-512.png"),
    join(ICONS, "apple-touch-icon.png"),
    join(ICONS, "favicon-16.png"),
    join(ICONS, "favicon-32.png"),
    join(ICONS, "favicon-48.png"),
  ];

  for (const file of opaqueSet) {
    it(`${file.slice(ROOT.length + 1)} is fully opaque`, async () => {
      const { data } = await raw(file);
      expect(minAlpha(data)).toBe(255);
    });
  }

  /**
   * The dark tile is gone. `apple-touch-icon-dark.png` was the one home-screen
   * tile under ADR-0015, pinned to the Void colorway; ADR-0017 replaced it with
   * the outlined tile under a name that carries no appearance. A file under the
   * old name would be an orphan the layout no longer links — and, worse, a
   * stale iOS capture target if a link to it ever crept back.
   */
  it("the dark tile no longer ships", () => {
    expect(readdirSync(ICONS)).not.toContain("apple-touch-icon-dark.png");
  });
});

/**
 * The OUTLINED colorway (ADR-0017) — what every installed surface carries.
 *
 * The contract, in pixels: a Laser plate; the mark FILLED in Laser; the mark
 * STROKED in Void. The point of the design is that the mark's legibility does
 * not depend on its plate — the Void outline carries it on the green plate, the
 * Laser fill carries it on a plate an OS has darkened — so what is pinned here
 * is exactly that both carriers are present. Stated as relationships and
 * channel orders, never as hexes: the hexes live in tokens.css, the generator
 * derives the ramp from them, and this file must not hold a second opinion
 * about the brand green (the failure tasks/lessons.md records).
 *
 * These replace the two colorway tests that stood here under ADR-0015, which
 * pinned the tile to the DARK colorway (plate darker than mark; the exact
 * inverse of the house tile). Both would now fail by design: the plate is the
 * light one again, and it is meant to be.
 */
describe("the outlined colorway — both carriers present on every installed tile", () => {
  const tiles = ["apple-touch-icon.png", "maskable-192.png", "maskable-512.png"];

  for (const file of tiles) {
    describe(file, () => {
      it("has a Laser plate — bright and green-led, not a dark one", async () => {
        const { plate } = await sampleTile(join(ICONS, file));
        expect(
          plate.luma,
          "the plate is the brand green, which is light",
        ).toBeGreaterThan(160);
        expectGreenLed(plate, "plate");
      });

      it("fills the mark in the plate's green, so a darkened plate cannot swallow it", async () => {
        const { mark } = await sampleTile(join(ICONS, file));
        expect(mark.luma, "the fill is the brand green, which is light").toBeGreaterThan(
          160,
        );
        expectGreenLed(mark, "mark fill");
      });

      it("outlines the mark in Void, so the green plate cannot swallow it either", async () => {
        const { outline, plate } = await sampleTile(join(ICONS, file));
        // Void's luma is ~16; anything under 48 is unmistakably the stroke and
        // not an antialiased edge of the green.
        expect(
          outline.luma,
          "no pixel dark enough to be the stroke on the row through the mark",
        ).toBeLessThan(48);
        expect(
          outline.luma,
          "the outline must be far darker than the plate",
        ).toBeLessThan(plate.luma / 3);
      });
    });
  }

  /**
   * The transparent `any` matrix carries the SAME two carriers, minus the
   * plate — a consumer paints its own ground behind an `any` icon, which is the
   * one case where the ground is genuinely unknown.
   */
  it("icon-512.png (the any matrix) is the outlined mark alone", async () => {
    const { mark, outline } = await sampleTile(join(ICONS, "icon-512.png"));
    expect(mark.luma).toBeGreaterThan(160);
    expectGreenLed(mark, "mark fill");
    expect(outline.luma).toBeLessThan(48);
    expect(outline.alpha, "the stroke is opaque, not a soft shadow").toBe(255);
  });
});

type Sample = {
  rgb: string;
  luma: number;
  alpha: number;
  r: number;
  g: number;
  b: number;
};

/** Green-led: G leads, R trails it, B is far behind — the shape of every stop
 *  on the Laser ramp, and of nothing on the Void one. */
function expectGreenLed({ r, g, b }: Sample, what: string) {
  expect(g, `${what}: green must lead`).toBeGreaterThan(r);
  expect(r, `${what}: red must lead blue (a lime, not a teal)`).toBeGreaterThan(b);
  expect(g, `${what}: green must be strong`).toBeGreaterThan(200);
}

/**
 * Three samples of any tile: the plate at (2, 2), the mark's fill at the
 * centre, and the darkest pixel on the row through the centre — which on the
 * outlined artwork is the stroke, and on flat artwork would be the mark.
 *
 * (2, 2) is plate on any full-bleed tile — these are flattened, so every pixel
 * outside the mark is the plate (a gradient, so its exact value varies by row;
 * the assertions above read its channel order, not its value). The CENTRE is
 * inside the mark's vertical bar at both glyph fractions this pipeline renders:
 * frac 0.74 puts the bar at 45.8–54.2 % of the width, frac 0.58 at 46.7–53.3 %,
 * and the bar spans the vertical centre in both.
 */
async function sampleTile(file: string) {
  const { data, info } = await raw(file);
  const at = (x: number, y: number): Sample => {
    const i = (y * info.width + x) * 4;
    const [r, g, b, alpha] = [data[i]!, data[i + 1]!, data[i + 2]!, data[i + 3]!];
    return {
      rgb: `${r},${g},${b}`,
      luma: 0.2126 * r + 0.7152 * g + 0.0722 * b,
      alpha,
      r,
      g,
      b,
    };
  };
  const cy = info.height >> 1;
  // The darkest OPAQUE pixel on the row: on a transparent `any` icon the row
  // starts in clear pixels (luma 0, alpha 0), which must not win.
  let outline: Sample | null = null;
  for (let x = 0; x < info.width; x++) {
    const s = at(x, cy);
    if (s.alpha === 255 && (outline === null || s.luma < outline.luma)) outline = s;
  }
  if (!outline) throw new Error(`${file}: no opaque pixel on the centre row`);
  return { plate: at(2, 2), mark: at(info.width >> 1, cy), outline };
}
