import { readdirSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";
import { describe, expect, it } from "vitest";

/**
 * Icon alpha contract (guardrail §6 / INV-09, audit INV-009): the `any`
 * matrix ships transparent PNGs; maskable, BOTH apple-touch appearances, and
 * the favicons are fully opaque (iOS expects a filled square and applies its
 * own mask). The suite is generated by scripts/generate-icons.mjs — this test
 * exists so a regeneration that flattens (or un-flattens) the wrong set fails
 * the gate instead of shipping.
 *
 * The App Router convention files (`src/app/icon0.svg`, `icon1.png`,
 * `apple-icon.png`) used to be listed here. They are gone: layout.tsx now
 * exports `metadata.icons`, which suppresses the convention links entirely, so
 * keeping the files would have shipped three assets nothing referenced.
 */
const ROOT = join(__dirname, "..", "..");
const ICONS = join(ROOT, "public", "icons");

async function raw(file: string) {
  const img = sharp(file);
  const meta = await img.metadata();
  const { data, info } = await img
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  return { meta, data, info };
}

function cornerAlphas(data: Buffer, width: number, height: number) {
  const px = (x: number, y: number) => data[(y * width + x) * 4 + 3];
  return [px(0, 0), px(width - 1, 0), px(0, height - 1), px(width - 1, height - 1)];
}

function minAlpha(data: Buffer) {
  let min = 255;
  for (let i = 3; i < data.length; i += 4) {
    const a = data[i];
    if (a !== undefined && a < min) min = a;
  }
  return min;
}

describe("icon alpha contract (transparent any-matrix, opaque masked set)", () => {
  const anyMatrix = readdirSync(ICONS).filter((f) => /^icon-\d+\.png$/.test(f));

  it("the any-matrix is present", () => {
    expect(anyMatrix.length).toBeGreaterThanOrEqual(13);
  });

  for (const file of anyMatrix) {
    it(`${file} keeps a transparent plate (alpha corners)`, async () => {
      const { meta, data, info } = await raw(join(ICONS, file));
      expect(meta.hasAlpha, "any-matrix icons must carry an alpha channel").toBe(true);
      for (const a of cornerAlphas(data, info.width, info.height)) {
        expect(a, "corner pixels outside the rounded plate must be transparent").toBe(0);
      }
    });
  }

  const opaqueSet = [
    join(ICONS, "maskable-192.png"),
    join(ICONS, "maskable-512.png"),
    join(ICONS, "apple-touch-icon.png"),
    join(ICONS, "apple-touch-icon-dark.png"),
    join(ICONS, "favicon-16.png"),
    join(ICONS, "favicon-32.png"),
    join(ICONS, "favicon-48.png"),
  ];

  for (const file of opaqueSet) {
    it(`${file.slice(ROOT.length + 1)} is fully opaque`, async () => {
      const { data } = await raw(file);
      expect(minAlpha(data)).toBe(255);
    });
  }

  /**
   * The two home-screen appearances must be genuine INVERSES of each other —
   * that is the whole point of shipping a second tile. A dark tile that merely
   * darkened the light one (which is what iOS does unaided) would leave Void
   * ink on a near-Void plate: the mark invisible, the bug this fixes.
   *
   * Sampled, not restated: the hexes live in tokens.css and the generator reads
   * them from there, so asserting `light.plate === dark.glyph` pins the
   * relationship without giving this file a second opinion about the brand
   * green. (2, 2) is plate on both; (90, 90) is inside the glyph's vertical bar
   * on both (the bar spans y 31.7–113.8 of the 180px tile at frac 0.74).
   */
  it("the two apple-touch appearances are inverse colorways", async () => {
    const sample = async (file: string) => {
      const { data, info } = await raw(file);
      const at = (x: number, y: number) => {
        const i = (y * info.width + x) * 4;
        return `${data[i]},${data[i + 1]},${data[i + 2]}`;
      };
      return { plate: at(2, 2), glyph: at(90, 90) };
    };
    const light = await sample(join(ICONS, "apple-touch-icon.png"));
    const dark = await sample(join(ICONS, "apple-touch-icon-dark.png"));

    expect(light.plate, "a tile whose plate equals its glyph shows nothing").not.toBe(
      light.glyph,
    );
    expect(dark.plate).not.toBe(dark.glyph);
    expect(dark.plate, "the dark tile's plate must be the light tile's ink").toBe(
      light.glyph,
    );
    expect(dark.glyph, "the dark tile's mark must be the light tile's plate").toBe(
      light.plate,
    );
  });
});
